version: '3'
services: 
  web: 
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    volumes: 
      - /usr/app/node_modules 
      - .:/usr/app
  tests: 
    build: 
      context: . 
      dockerfile: Dockerfile.dev 
    volumes: 
      - /usr/app/node_modules 
      - .:/usr/app 
    command: ["npm", "run", "test"]  
